### ISSUE TITLE
Binance api fee is incorrect

### ISSUE THREAD

**Issue by lookfirst** [JulyIGHOR/QtBitcoinTrader#239]
My fee is 0.075 and the UX reports that it is 0.1

Also cannot set it to 3 decimals in the UX (in the calculator)

**Comment by JulyIGHOR** [comment]
Qt Bitcoin Trader not yet supports different fees for maker and taker, so this is delayed.
3 decimals in the UX fixed now

**Comment by lookfirst** [comment]
I have the same fee for both, so that is fine. Just needed the 3 decimals.

**Comment by lookfirst** [comment]
@JulyIGHOR Fixed in the calculator, but not on the main screen:

![image](https://user-images.githubusercontent.com/85355/48975651-62596d80-f0a8-11e8-9a69-565d4500d5df.png)

**Comment by JulyIGHOR** [comment]
Please confirm, is it fixed in 1.40.40?

**Comment by JulyIGHOR** [comment]
Please

> @JulyIGHOR Fixed in the calculator, but not on the main screen:
> 
> ![image](https://user-images.githubusercontent.com/85355/48975651-62596d80-f0a8-11e8-9a69-565d4500d5df.png)

Please open Debug dialog, catch few minutes traffic, save it to file and send here or to my email julyighor@gmail.com

**Comment by lookfirst** [comment]
Not fixed

Interestingly enough, I don't see the fee anywhere in the debug output. 

Sorry, I won't send it to you since it has my account data in it.

**Comment by lookfirst** [comment]
I should add that when I close the debug window by clicking on the close icon, it reliably crashes the app.

**Comment by lookfirst** [comment]
![image](https://user-images.githubusercontent.com/85355/50580789-c3354c00-0e85-11e9-8cc3-bb6567f22754.png)

I see the issue. I'm using BNB to pay for my fees, which lowers them to 0.075, so that is why it is not showing up in your app correctly.

**Comment by JulyIGHOR** [comment]
> Sorry, I won't send it to you since it has my account data in it.
There should be no account data, if you can find it there, let me know which kind it is and we will fix it.

> I should add that when I close the debug window by clicking on the close icon, it reliably crashes the app.
Thanks for bug report.

Qt Bitcoin Trader takes fee value from API and info looks like this:

{
"makerCommission":10,
"takerCommission":10,
"buyerCommission":0,
"sellerCommission":0,
"canTrade":true,
"canWithdraw":true,
"canDeposit":true,
"updateTime":1531843812787,
"balances":[]
}

If you can find another values that contains your fee 0.075 in Debug log, please send this part of code and we will try to fix it.

**Comment by lookfirst** [comment]
I doubt it is in the API. The key here is to just allow me to check a box saying that I'm using BNB to pay for my fees. This will lower the fee by the current 25%.

https://support.binance.com/hc/en-us/articles/115000583311

**Comment by lookfirst** [comment]
@JulyIghor The way to fix it is to hardcode the value for now. It isn't in their api.
